const template = `
The following commits do not follow the [Shopistan Commits][cc] rules:

<PLACEHOLDER>

<details>

<DETAILS>

</details>

You may need to [change the commit messages][ref] to comply with the \
repository contributing guidelines.

--------

This comment was generated by [**pro-commitlint[bot]**][repo]. 


[cc]: https://ammar-ahmed-butt.atlassian.net/wiki/spaces/PP/pages/62600256
[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/ammar-ahmed-butt/commitlint-bot
`;

/**
 * Formats array of commits warnings/errors as GitHub comment
 *
 * @param {Array} report
 */
function format(commits) {
	let details = '';
	let message = commits.map(c => `* ${c.sha}`).join('\n');

	commits.forEach(c => {
		details += `* Commit: ${c.sha}\n`;
		details += c.errors.map(e => `  - ✖ ${e.message}\n`).join('');
		details += c.warnings.map(w => `  - ⚠ ${w.message}\n`).join('');
	});

	return template
		.replace('<PLACEHOLDER>', message)
		.replace('<DETAILS>', details);
}

module.exports = format;
